### ISSUE TITLE
Add the possibility to define and choose alternative decorators. 

### ISSUE THREAD

**Issue by manudss** [smartinio/bitbucket-conventional-comments#14]
Should be grate to have more decorator, and have the possibility to have more decorators.

**Comment by manudss** [comment]
Hi @smartinio,

What do you think, about adding possibilities to have more decorators, with a new selector like this : 
![image](https://user-images.githubusercontent.com/1046806/217945966-70246ab7-fa21-4eee-a518-678cbf477b9e.png)

Every time, you have selects one decorator, it will update the prefix of comment to add (or remove) the decorators. 

This list of decorators could be defined in settings. Maybe have a different list for each label. 

With this, we could remove duplicate button, for blocking and non-blocking buttons.

**Comment by manudss** [comment]
Hi @smartinio, 
I'm currently working, on this feature. But I would like to have your feedback about this, because, it was a important change about your extension. 
I have implemented something like this : 
![sidekick_UVbe6MJpUG](https://user-images.githubusercontent.com/1046806/219666097-baf3707b-a2d2-4e42-b9db-51cf36af66d4.gif)

What do you think ? Are you agreeing to add something like this ?

**Comment by smartinio** [comment]
Looks useful, but how does it look on smaller screens / side-by-side views? Maybe the checkboxes can be positioned under the icons?

**Comment by manudss** [comment]
Yes, there are still some adjustments to make. I just wanted to have your opinion before continuing. And you're right, for the checkboxes if you're on a small screen, I just made the change to go underneath.
![image](https://user-images.githubusercontent.com/1046806/220312078-d73d13f4-41e6-4689-b8a6-97ba99b81a96.png)
