### ISSUE TITLE
Does not works with bitbucket.org 

### ISSUE THREAD

**Issue by manudss** [smartinio/bitbucket-conventional-comments#21]
Update the extention to make it works for Bitbucket online. 

Works only for now in Bitbucket server.

**Comment by grunk** [comment]
Hello, i just installed your extension from the chrome webstore and it does not appears on bitbucket.org.
The extension is enabled.
I tried to disabled the Atlassian Editor in the "Labs" of bitbucket without any success.

Is it supposed to work ?
Anything i can do to give you more information ?

**Comment by manudss** [comment]
Hi @grunk,

Effectivement, cela ne fonctionne plus. Ils ont changé leurs sélecteurs. Je regarde pour faire une nouvelle version.  Comme je ne l'utilise pas la version cloud, je n'ai pas vu que cela ne fonctionnait plus.
