### ISSUE TITLE
fix bitbucket.org new versions 

### ISSUE THREAD

**Issue by manudss** [smartinio/bitbucket-conventional-comments#27]
Does not works well with new versions of bitbucket.org #21 as requested in last comments. 

- try to use a more robust selector from bitbucket.org to select elements. Avoid generated css class.

**Comment by StevenRoodhorst** [comment]
Any update on this? The extension is not working for Bitbucket cloud.

**Comment by smartinio** [comment]
@StevenRoodhorst I don't work in Bitbucket anymore so I don't actively maintain this. PRs are welcome.

**Comment by manudss** [comment]
Hello, 

I made changes to make it works on bitbucket.org. I don't use bitbucket.org also. So PRs are welcome, if there is other issue. 

Need to merge #28
